export const searchLabels: Record<string, string> = {
  finalidade: "Finalidade",
  tipo: "Tipo de imóvel",
  cidade: "Cidade",
  bairro: "Bairro",
  referencia: "Referência",
  q: "Tipo, cidade ou bairro",
  contagem: "Quantidade de cômodos",
  dormitorios: "Dormitórios",
  banheiros: "Banheiros",
  suites: "Suítes",
  vagas: "Vagas",
  precoMin: "Valor mínimo (R$)",
  precoMax: "Valor máximo (R$)",
  areaMin: "Área mínima (m²)",
  areaMax: "Área máxima (m²)",
  areaTipo: "Medida de área",
  mobiliado: "Mobiliado",
  permuta: "Aceita permuta",
  financiamento: "Aceita financiamento",
  fotos: "Com fotos",
  estagio: "Estágio",
  valorModo: "Forma do preço",
  exata: "Correspondência da referência",
};
